<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MacBook-Pro-di-Anna.local" failures="0" tests="8" name="com.hotels.beans.validator.ValidatorTest" time="1.461" errors="0" timestamp="26 mag 2019 20:28:21 GMT" skipped="0">
  <testcase classname="com.hotels.beans.validator.ValidatorTest" name="testNotNullRaisesAnExceptionWhenTheGivenObjectIsNull" time="0.000"/>
  <testcase classname="com.hotels.beans.validator.ValidatorTest" name="testThatNoExceptionAreThrownWhenTheGivenObjectIsNotNullEvenWithoutACustomMessage" time="0.000"/>
  <testcase classname="com.hotels.beans.validator.ValidatorTest" name="testValidateDoesNotThrowsExceptionWhenTheBeanIsValid" time="0.000"/>
  <testcase classname="com.hotels.beans.validator.ValidatorTest" name="testNotNullRaisesAnExceptionWhenTheGivenObjectIsNull" time="0.000"/>
  <testcase classname="com.hotels.beans.validator.ValidatorTest" name="testGetConstraintViolationsWorksAsExpected" time="1.396"/>
  <testcase classname="com.hotels.beans.validator.ValidatorTest" name="testThatNoExceptionAreThrownWhenTheGivenObjectIsNotNullEvenWithoutACustomMessage" time="0.000"/>
  <testcase classname="com.hotels.beans.validator.ValidatorTest" name="testGetConstraintViolationsWorksAsExpected" time="0.062"/>
  <testcase classname="com.hotels.beans.validator.ValidatorTest" name="testValidateThrowsExceptionWhenTheBeanIsInvalid" time="0.003"/>
</testsuite> <!-- com.hotels.beans.validator.ValidatorTest -->
